Investigating Windows 3.x
	What is the registry key with the encoded payload? (full path)
		HKCU\Software\Microsoft\Windows\CurrentVersion\Debug
	What is the rule name for this run key generated by Sysmon?
		T1547.001
	What tactics is classified with this MITRE ATT&CK ID?
		Persistence, Priviledge Escalation
	What was UTC time for the Sysmon event?
		2021-01-22 01:08:13.468
	What was the Sysmon Event ID? Event Type? (answer, answer)
		13, SetValue
	Decode the payload. What service will the payload attempt start?
		Fax
	The payload attempts to open a local port. What is the port number?
		9299
	What process does the payload attempt to terminate?
		FXSSVC
	What DLL file does the payload attempt to remove? (full path)
		C:\Windows\System32\ualapi.dll
	What is the Windows Event ID associated with this service?
		823
	What is listed as the New Default Printer?
		PrintDemon
	What process is associated with this event?
		spoolsv.exe
	What is the parent PID for the above process?
		620
	Examine the other processes. What is the PID of the process running the encoded payload?
		3088
	Decode the payload. What is the a visible partial path?
		/admin/get.php
	This is the default communication profile the agent used to connect to the attack machine. What attack framework was used? What is the name of the variable? (answer, answer)
		DefaultProfile, Empire
	What other file paths are you likely to find in the logs? (answer, answer)
		/news.php, /login/process.php
	What is the MITRE ATT&CK URI for the attack framework?
		https://attack.mitre.org/software/S0363/
	What was the FQDN of the attacker machine that the suspicious process connected to?
		ec2-34-245-128-161.eu-west-1.compute.amazonaws.com
	What other process connected to the attacker machine?
		Explorer.exe
	What is the PID for this process?
		2684
	What was the path for the first image loaded for the process identified in Q's 19 & 20?
		C:\Windows\System32\mscoree.dll
	What Sysmon event was generated between these 2 processes? What is its associated Event ID #? (answer, answer)
		CreateRemoteThread, 8
	What is the UTC time for the first event between these 2 processes?
		2021-01-22 01:07:06.182
	What is the value under Date and Time? (MM/DD/YYYY H:MM:SS [AM/PM])
		1/21/2021 5:07:06 PM
	What is the first operation listed by the 2nd process starting with the Date and Time from Q25?
		Thread Create
	What is the full registry path that was queried by the attacker to get information about the victim?
		HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\ReleaseId
	What is the name of the last module in the stack from this event which had a successful result?
		<unknown>
	Most likely what module within the attack framework was used between the 2 processes?
		Invoke-PSInject
	What is the MITRE ID for this technique?
		T1055
